runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  DATABASE_URL: ""
  OAUTH_CLIENT_ID: "${{ secrets.OAUTH_CLIENT_ID }}"
  OAUTH_CLIENT_SECRET: "${{ secrets.OAUTH_CLIENT_SECRET }}"
