apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-tracker
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-tracker
  template:
    metadata:
      labels:
        app: finance-tracker
    spec:
      containers:
        - name: finance-tracker
          image: gcr.io/${{ env.GOOGLE_PROJECT_ID }}/finance-tracker:${{ env.BUILD_TAG }}
          ports:
            - containerPort: 8080
